### ISSUE TITLE
Update versions of Xtend and Xtext

### ISSUE THREAD

**Issue by TomCLForwood** [REGnosys/rosetta-dsl#31]
The versions of Xtext and Xtend currently being used (2.15.0) only supports up to Java 8.
We need to be able to move to a fully supported version of Java.

**Comment by SimonCockx** [comment]
Since https://github.com/REGnosys/rosetta-dsl/pull/348 we're on version 2.25 of Xtext. The current latest release is 2.27. I'll try to update this next week.

> Nowadays, the usage of Xtend is actually discouraged by the developers of Xtext. See https://github.com/eclipse/xtext-core/issues/1223 and [this blog post](https://www.salvis.com/blog/2020/06/06/bye-bye-xtend-welcome-java/). Not that this is a big priority, but wouldn't it be better to move away from Xtend? That would make it easier to keep up with the new Java versions, especially because a developer of Xtend said in 2019 "we dont have the capacity to maintain and develop Xtend in a way that would / should / could encourage users to use it as GPL" (see discussion linked above). It seems that almost all problems that Xtend set out to solve, are already solved in the newest Java versions.

To answer myself: while this is true, there currently is no alternative as great as Xtend for stuff like code generation and writing clear tests for Rosetta models. We will keep using Xtend for these cases, but will switch to plain Java by default for anything else.
