### ISSUE TITLE
Remove dupcliates from List 

### ISSUE THREAD

**Issue by hugohills-regnosys** [REGnosys/rosetta-dsl#326]
ListOperation syntax should either work with existing `distinct` syntax or the `distinct` syntax should be refactored to work with the new approach.

```
type Foo:
		include boolean (1..1)
		attr string (1..1)
	
	func FuncFoo:
			inputs:
			 foos Foo (0..*)
		output:
			filteredFoosDistinct Foo (0..*)
		
		set filteredFoosDistinct:
			foos 
				filter fooItem [ fooItem -> include = True ]
				distinct
```

See section "Removal of Duplicate Items" of the FunctionIteratorTechicalSpecification document.

**Comment by dhuebner** [comment]
@hugohills-regnosys 
I would definitely suggest to use ListOperation in such cases. Other candidates are `only-element`, `count`, `group-by`
It is better to have one common way to work with Lists instead of having different Language features to achieve the same. It is more important to have less duplicate constructs as we are targeting a non-programmer users.
